version: "3.8"
services:
  product-catalog-service:
    depends_on:
      - postgres
    image: "product-catalog-service"
    container_name: "product-catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - JAVA_OPTS=-XX:ReservedCodeCacheSize=32M -XX:MaxDirectMemorySize=32M
      - BPL_JVM_THREAD_COUNT=20
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://my-shoppingapp-configservice:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/myshoppingappdb
      - SPRING_PROFILES_ACTIVE=testdata
  
  product-config-service:
    image: "my-shoppingapp-configservice"
    container_name: "my-shoppingapp-configservice"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      - BPL_JVM_THREAD_COUNT=20
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888

  postgres:
    image: "postgres:latest"
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myshoppingappdb
