version: "3.8"
services:
  product-catalog-service:
    depends_on:
      - postgres
    image: "product-catalog-service"
    container_name: "product-catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 8001
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://my-shoppingapp-configservice:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/myshoppingcatalogdb
      - SPRING_PROFILES_ACTIVE=testdata

  order-service:
    depends_on:
      - postgres
    image: "order-service"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8002
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - CATALOG_SERVICE_URI=http://product-catalog-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://my-shoppingapp-configservice:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/myshoppingapporderdb
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/myshoppingapporderdb

  config-service:
    image: "config-service"
    container_name: "config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 9888
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888

  # Backing Services

  postgres:
    image: "postgres:latest"
    container_name: "init.sqlpostgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
